apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghost
  # You'll usually want to add your resources to the argocd namespace.
  namespace: {{.Release.Namespace}}
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  # Add labels to your application object.
  labels:
    name: {{.Release.Name}}-ghost
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  # The project the application belongs to.
  project: proj-{{.Release.Namespace}}

  # Source of the application manifests
  source:
    repoURL: https://charts.bitnami.com/bitnami  # Can point to either a Helm chart repo or a git repo.
    targetRevision: "19.3.6"  # For Helm, this refers to the chart version.
    
    chart: ghost
    helm:
      passCredentials: false # If true then adds --pass-credentials to Helm commands to pass credentials to all domains
      # Extra parameters to set (same as setting through values.yaml, but these take precedence)

      # Release name override (defaults to application name)
      releaseName: ghost
      version: v3
      values: |
        ghostPassword: randomPassword
        ghostHost: ghost.{{.Release.Namespace}}.findi.biz
        smtpHost: "smtp4dev.{{.Release.Namespace}}.svc"
        smtpPort: "25"
        smtpUser: "anyuser"
        smtpPassword: "anypassword"
        smtpService: "Mailgun"
        podAnnotations:
          sidecar.istio.io/inject: "false"
        service:
          type: ClusterIP
        ghostEnableHttps: false
        persistence:
          enabled: true
          size: 1Gi
        updateStrategy:
          type: Recreate
        mysql:
          enabled: true
          primary:
            podAnnotations:
              sidecar.istio.io/inject: "false"
        ingress:
          enabled: true
          hostname: ghost.{{.Release.Namespace}}.findi.biz
          tls: true
          annotations:
            external-dns: "true"

  # Destination cluster and namespace to deploy the application
  destination:
    name: gke-us-east1
    # The namespace will only be set for namespace-scoped resources that have not set a value for .metadata.namespace
    namespace: {{.Release.Namespace}}

  # Sync policy
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default ).
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
    - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
    - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
    # The retry feature is available since v1.7
    - RespectIgnoreDifferences=true
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy

  # Will ignore differences between live and desired states during the diff. Note that these configurations are not
  # used during the sync process.
  ignoreDifferences:
  # for the specified json pointers
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  # for the specified managedFields managers
  - group: "*"
    kind: "*"
    managedFieldsManagers:
